# Generated by Django 6.0.2 on 2026-02-28 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sales",
            old_name="cliente",
            new_name="customer",
        ),
    ]
