# Generated by Django 6.0.2 on 2026-02-28 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Inactive"), (1, "Active")], default=1
            ),
        ),
    ]
